"""
Professional Chart Generator for Aadhaar Demographic Update Analysis
UIDAI Data Hackathon 2026
Author: Team Analysis (Generated by Antigravity)
Dataset: Demographic Update Data (Address, Name, DOB changes)
"""

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import numpy as np
import glob
import os

# Set professional styling
plt.style.use('seaborn-v0_8-whitegrid')
plt.rcParams['font.family'] = 'sans-serif'
plt.rcParams['font.sans-serif'] = ['Arial', 'Helvetica', 'DejaVu Sans']
plt.rcParams['font.size'] = 11
plt.rcParams['axes.labelsize'] = 12
plt.rcParams['axes.titlesize'] = 14
plt.rcParams['axes.titleweight'] = 'bold'

# Professional color palette - Different from biometric (green theme)
COLORS = {
    'primary': '#2D6A4F',      # Forest Green
    'secondary': '#40916C',    # Medium Green
    'accent': '#95D5B2',       # Light Green
    'highlight': '#D8F3DC',    # Very Light Green
    'dark': '#1B4332',         # Dark Green
    'warning': '#E63946',      # Red for anomalies
}

def format_lakhs(x, pos):
    """Format numbers in Lakhs for Indian context"""
    if x >= 100000:
        return f'{x/100000:.1f}L'
    elif x >= 1000:
        return f'{x/1000:.0f}K'
    return f'{x:.0f}'

def add_value_labels(ax, bars, format_func=None):
    """Add value labels on top of bars"""
    for bar in bars:
        height = bar.get_height()
        if format_func:
            label = format_func(height)
        else:
            label = f'{height/100000:.1f}L' if height >= 100000 else f'{height/1000:.0f}K'
        ax.annotate(label,
                    xy=(bar.get_x() + bar.get_width() / 2, height),
                    xytext=(0, 3),
                    textcoords="offset points",
                    ha='center', va='bottom',
                    fontsize=10, fontweight='bold',
                    color='#333333')

def load_demographic_data():
    """Load all demographic update CSV files"""
    print("📂 Loading demographic update data...")
    data_path = "../../datasets/api_data_aadhar_demographic/*.csv"
    files = glob.glob(data_path)
    
    if not files:
        # Try alternate path
        data_path = "../datasets/api_data_aadhar_demographic/*.csv"
        files = glob.glob(data_path)
    
    if not files:
        raise FileNotFoundError("Could not find demographic data files!")
    
    df_list = [pd.read_csv(f) for f in files]
    df = pd.concat(df_list, ignore_index=True)
    
    # Clean data
    df.drop_duplicates(inplace=True)
    df.fillna(0, inplace=True)
    df['total_updates'] = df['demo_age_5_17'] + df['demo_age_17_']
    
    print(f"   ✅ Loaded {len(df):,} records from {len(files)} files\n")
    return df

def create_age_group_chart(df):
    """Create professional age group vs demographic updates chart"""
    # Calculate raw values
    age_5_17_total = df['demo_age_5_17'].sum()
    age_17_plus_total = df['demo_age_17_'].sum()
    
    age_totals = {
        '5-17 Years\n(Children & Teens)': age_5_17_total,
        '17+ Years\n(Adults)': age_17_plus_total
    }
    
    fig, ax = plt.subplots(figsize=(10, 7))
    
    colors = [COLORS['secondary'], COLORS['primary']]
    
    bars = ax.bar(age_totals.keys(), age_totals.values(), color=colors, 
                  edgecolor='#333333', linewidth=1.2, width=0.5)
    
    # Add value labels
    add_value_labels(ax, bars)
    
    # Add percentage labels
    total = sum(age_totals.values())
    for i, (bar, val) in enumerate(zip(bars, age_totals.values())):
        percentage = (val / total) * 100
        ax.annotate(f'({percentage:.1f}%)',
                    xy=(bar.get_x() + bar.get_width() / 2, bar.get_height() / 2),
                    ha='center', va='center',
                    fontsize=12, fontweight='bold',
                    color='white')
    
    ax.set_xlabel('Age Group', fontsize=12, fontweight='bold', color='#333333')
    ax.set_ylabel('Total Demographic Updates', fontsize=12, fontweight='bold', color='#333333')
    ax.set_title('Demographic Update Distribution by Age Group\n(Address, Name, DOB Changes)', 
                 fontsize=14, fontweight='bold', color=COLORS['dark'], pad=20)
    
    ax.yaxis.set_major_formatter(ticker.FuncFormatter(format_lakhs))
    ax.yaxis.grid(True, linestyle='--', alpha=0.7)
    ax.set_axisbelow(True)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    
    insight_text = "Key Insight: Adults dominate\ndemographic updates, indicating\nmigration and life-stage changes"
    props = dict(boxstyle='round,pad=0.5', facecolor=COLORS['highlight'], edgecolor=COLORS['primary'], alpha=0.9)
    ax.text(0.98, 0.98, insight_text, transform=ax.transAxes, fontsize=9,
            verticalalignment='top', horizontalalignment='right', bbox=props)
    
    fig.text(0.99, 0.01, 'Source: UIDAI Anonymised Dataset | UIDAI Hackathon 2026', 
             ha='right', va='bottom', fontsize=8, color='#666666', style='italic')
    
    plt.tight_layout()
    plt.savefig('age_group_demographic_professional.png', dpi=300, bbox_inches='tight',
                facecolor='white', edgecolor='none')
    plt.close()
    print("✅ Generated: age_group_demographic_professional.png")
    
    # Return raw values for summary
    return {'age_5_17': age_5_17_total, 'age_17_plus': age_17_plus_total}

def create_state_wise_chart(df):
    """Create professional state-wise demographic update chart"""
    state_updates = df.groupby('state')['total_updates'].sum().sort_values(ascending=False).head(10)
    
    fig, ax = plt.subplots(figsize=(12, 7))
    
    colors = plt.cm.Greens(np.linspace(0.8, 0.4, len(state_updates)))
    
    bars = ax.bar(range(len(state_updates)), state_updates.values, 
                  color=colors, edgecolor=COLORS['dark'], linewidth=1.2)
    
    add_value_labels(ax, bars)
    
    ax.set_xlabel('State', fontsize=12, fontweight='bold', color='#333333')
    ax.set_ylabel('Total Demographic Updates', fontsize=12, fontweight='bold', color='#333333')
    ax.set_title('Top 10 States by Demographic Update Frequency\n(Migration and Address Change Patterns)', 
                 fontsize=14, fontweight='bold', color=COLORS['dark'], pad=20)
    
    ax.set_xticks(range(len(state_updates)))
    ax.set_xticklabels(state_updates.index, rotation=45, ha='right', fontsize=10)
    
    ax.yaxis.set_major_formatter(ticker.FuncFormatter(format_lakhs))
    ax.yaxis.grid(True, linestyle='--', alpha=0.7)
    ax.set_axisbelow(True)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    
    fig.text(0.99, 0.01, 'Source: UIDAI Anonymised Dataset | UIDAI Hackathon 2026', 
             ha='right', va='bottom', fontsize=8, color='#666666', style='italic')
    
    plt.tight_layout()
    plt.savefig('state_wise_demographic_professional.png', dpi=300, bbox_inches='tight',
                facecolor='white', edgecolor='none')
    plt.close()
    print("✅ Generated: state_wise_demographic_professional.png")
    
    return state_updates

def create_time_trend_chart(df):
    """Create time-based demographic update trend chart"""
    df_copy = df.copy()
    df_copy['date'] = pd.to_datetime(df_copy['date'], dayfirst=True)
    
    daily_updates = df_copy.groupby('date')['total_updates'].sum().reset_index()
    daily_updates = daily_updates.sort_values('date')
    
    fig, ax = plt.subplots(figsize=(14, 6))
    
    ax.fill_between(daily_updates['date'], daily_updates['total_updates'], 
                    alpha=0.3, color=COLORS['primary'])
    ax.plot(daily_updates['date'], daily_updates['total_updates'], 
            color=COLORS['primary'], linewidth=2, marker='', label='Daily Updates')
    
    if len(daily_updates) > 7:
        daily_updates['ma_7'] = daily_updates['total_updates'].rolling(window=7).mean()
        ax.plot(daily_updates['date'], daily_updates['ma_7'], 
                color=COLORS['warning'], linewidth=2.5, linestyle='--', 
                label='7-Day Moving Average')
    
    peak_idx = daily_updates['total_updates'].idxmax()
    peak_date = daily_updates.loc[peak_idx, 'date']
    peak_value = daily_updates.loc[peak_idx, 'total_updates']
    ax.annotate(f'Peak: {peak_value/100000:.1f}L',
                xy=(peak_date, peak_value),
                xytext=(10, 20), textcoords='offset points',
                fontsize=9, fontweight='bold',
                arrowprops=dict(arrowstyle='->', color=COLORS['dark']),
                color=COLORS['dark'])
    ax.scatter([peak_date], [peak_value], color=COLORS['dark'], s=100, zorder=5)
    
    ax.set_xlabel('Date', fontsize=12, fontweight='bold', color='#333333')
    ax.set_ylabel('Total Demographic Updates', fontsize=12, fontweight='bold', color='#333333')
    ax.set_title('Demographic Update Trend Over Time\n(Address/Name/DOB Changes Pattern)', 
                 fontsize=14, fontweight='bold', color=COLORS['dark'], pad=20)
    
    ax.yaxis.set_major_formatter(ticker.FuncFormatter(format_lakhs))
    ax.xaxis.set_major_locator(plt.MaxNLocator(10))
    plt.xticks(rotation=45, ha='right')
    
    ax.legend(loc='upper right', framealpha=0.9)
    ax.grid(True, linestyle='--', alpha=0.5)
    ax.set_axisbelow(True)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    
    fig.text(0.99, 0.01, 'Source: UIDAI Anonymised Dataset | UIDAI Hackathon 2026', 
             ha='right', va='bottom', fontsize=8, color='#666666', style='italic')
    
    plt.tight_layout()
    plt.savefig('demographic_trend_professional.png', dpi=300, bbox_inches='tight',
                facecolor='white', edgecolor='none')
    plt.close()
    print("✅ Generated: demographic_trend_professional.png")

def create_update_type_comparison(df):
    """Create comparison showing demographic update reasons/patterns"""
    # Compare children vs adults for potential migration signals
    df_copy = df.copy()
    df_copy['date'] = pd.to_datetime(df_copy['date'], dayfirst=True)
    df_copy['month'] = df_copy['date'].dt.to_period('M')
    
    monthly = df_copy.groupby('month').agg({
        'demo_age_5_17': 'sum',
        'demo_age_17_': 'sum'
    }).reset_index()
    monthly['month'] = monthly['month'].astype(str)
    
    fig, ax = plt.subplots(figsize=(14, 6))
    
    x = range(len(monthly))
    width = 0.35
    
    bars1 = ax.bar([i - width/2 for i in x], monthly['demo_age_5_17'], width, 
                   label='5-17 Years', color=COLORS['secondary'], edgecolor='white')
    bars2 = ax.bar([i + width/2 for i in x], monthly['demo_age_17_'], width, 
                   label='17+ Years', color=COLORS['primary'], edgecolor='white')
    
    ax.set_xlabel('Month', fontsize=12, fontweight='bold', color='#333333')
    ax.set_ylabel('Total Demographic Updates', fontsize=12, fontweight='bold', color='#333333')
    ax.set_title('Monthly Demographic Updates by Age Group\n(Tracking Migration and Life-Stage Transitions)', 
                 fontsize=14, fontweight='bold', color=COLORS['dark'], pad=20)
    
    ax.set_xticks(x)
    ax.set_xticklabels(monthly['month'], rotation=45, ha='right', fontsize=9)
    
    ax.yaxis.set_major_formatter(ticker.FuncFormatter(format_lakhs))
    ax.legend(loc='upper right', framealpha=0.9)
    ax.yaxis.grid(True, linestyle='--', alpha=0.5)
    ax.set_axisbelow(True)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    
    fig.text(0.99, 0.01, 'Source: UIDAI Anonymised Dataset | UIDAI Hackathon 2026', 
             ha='right', va='bottom', fontsize=8, color='#666666', style='italic')
    
    plt.tight_layout()
    plt.savefig('monthly_demographic_comparison.png', dpi=300, bbox_inches='tight',
                facecolor='white', edgecolor='none')
    plt.close()
    print("✅ Generated: monthly_demographic_comparison.png")

def main():
    print("\n" + "="*60)
    print("🎨 UIDAI Demographic Update - Professional Chart Generator")
    print("="*60 + "\n")
    
    # Load data
    df = load_demographic_data()
    
    # Generate charts
    print("📊 Generating professional charts...\n")
    
    age_totals = create_age_group_chart(df)
    state_updates = create_state_wise_chart(df)
    create_time_trend_chart(df)
    create_update_type_comparison(df)
    
    # Save cleaned data
    print("\n💾 Saving cleaned dataset...")
    df.to_csv('clean_aadhaar_demographic.csv', index=False)
    print(f"   ✅ Saved: clean_aadhaar_demographic.csv ({len(df):,} records)")
    
    # Print summary stats
    print("\n" + "-"*60)
    print("📈 ANALYSIS SUMMARY")
    print("-"*60)
    print(f"   Total Records: {len(df):,}")
    print(f"   5-17 Age Updates: {age_totals['age_5_17']:,.0f}")
    print(f"   17+ Age Updates: {age_totals['age_17_plus']:,.0f}")
    print(f"   Top State: {state_updates.index[0]} ({state_updates.values[0]/100000:.1f}L)")
    
    print("\n" + "="*60)
    print("✅ All professional charts generated successfully!")
    print("="*60 + "\n")

if __name__ == "__main__":
    main()
